# Generated by Django 4.2.3 on 2023-10-04 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='stock',
        ),
    ]
