# Generated by Django 4.2.3 on 2023-10-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_rename_quantity_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='copoun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('discount', models.IntegerField()),
            ],
        ),
    ]
