# Generated by Django 4.2.3 on 2023-10-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_alter_address_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
