# Generated by Django 4.2.3 on 2023-10-16 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_wallet_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='balance',
        ),
    ]
