# Generated by Django 4.2.3 on 2023-10-21 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feedback',
        ),
    ]
