# Generated by Django 4.2.3 on 2023-10-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='last_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
